readonlyrest:
  enable: true
  #  ssl:
  #  enable: true
  #  keystore_file: "/usr/share/elasticsearch/config/self.jks"
  #  keystore_pass: ELASTICSEARCH_PASSWORD
  #  key_pass: ELASTICSEARCH_PASSWORD
  #  #allowed_protocols: ["TLSv1.2"]
  #  #allowed_ciphers: ["TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"]

  response_if_req_forbidden: Not authorized

  #rest.action.multi.allow_explicit_index: false

  access_control_rules:

  - name: "::LOCALHOST::"
    type: allow
    hosts: [127.0.0.1, localhost]
    verbosity: error

  - name: "::CHECK_MK::"
    type: allow
    hosts: [CHECKHEALTH]
    actions: ["cluster:monitor/health"]
    verbosity: error

  - name: "::LOGSTASH::"
    auth_key: LOGSTASH_RW_USERNAME:LOGSTASH_RW_PASSWORD
    type: allow
    hosts: [172.0.0.0/6]
    #hosts: [172.17.0.0/16]
    verbosity: error

  - name: "::KIBANA_RW::"
    auth_key: ELASTICSEARCH_USERNAME:ELASTICSEARCH_PASSWORD
    type: allow
    #hosts: [192.168.0.0/16]
    #indices: [".kibana"]
    verbosity: error

  - name: "::KIBANA_RO::"
    #-RO-auth_key: KIBANA_RO_USERNAME:KIBANA_RO_PASSWORD
    type: allow
    kibana_access: ro_strict
    #indices: [".kibana"]
    verbosity: error
    #hosts: [10.92.27.135]
